Vfd 166 mallimuutokset atf sovellukseen
Virtual-Finland-Development/access-to-finland-demo-front pull request #18
Opened 2023-01-04 14:23 UTC by LauriGofore

2023-01-11 17:17 UTC, lsipii requested changes
Näyttää hyvältä ja toimii hienosti! Voisi ainakin tuon työnhaku-sivun ekan latauksen bugin ehjätä, jos ei ohjeilla toistu niin lähetä minulle bumerangina takaisin.

2023-01-12 09:10 UTC, LauriGofore commented on src/components/VacanciesPage/VacanciesPage.tsx
> +  console.log(jobPostings);
Joo eipä nämä koskaan tarkoituksella jää tuonne, pitäisi siivoilla aina pois. Ja joo onhan noitan tooleja et siivoo buildatessa nuo pois. 👍

2023-01-12 09:11 UTC, LauriGofore commented on src/components/JmfRecommendationsSelect/MoreRecommendations.tsx
> +      loadOptions={loadMoreDebounced}
Tää on vähä sellane et pitäis joku kultainen keskitie keksiä, onko esim 1 sekunti liikaa? :D Mutta voihan tuota vähän nostella. 👍

2023-01-12 13:19 UTC, LauriGofore commented on src/components/VacanciesPage/VacanciesPage.tsx
> +export default function VacanciesPage() {
Tähän nyt tehty parannuksia - komponentin state oli vähän epäsyncassa initial tilanteessa. Nyt tuo initial syncci pitäis olla paremmalla tolalla + muutenkin staten muutoksen händläykseen pieniä parannuksia.

2023-01-13 08:56 UTC, lassipatanen approved these changes

2023-01-13 08:59 UTC, lsipii approved these changes

2023-01-13 09:16 UTC, merged